stages:
  train:
    cmd: py src/train.py
    deps:
      - data/Iris.csv
      - src/train.py
    params:
      - train.n_estimators
      - train.random_state
      - train.test_size
    outs:
      - models/random_forest.pkl
    metrics:
      - results/metrics.json